from ChampionBaseClass import Champion


Aatrox = Champion("Aatrox", True, 3, 3, 2, 2, 2, 2)
Ahri = Champion("Ahri", False, 3, 1, 2, 3, 0, 2)
Akali = Champion("Akali", True, 3, 1, 1, 3, 1, 2)
Alistar = Champion("Alistar", True, 1, 3, 3, 1, 2, 1)
Amumu = Champion("Amumu", True, 2, 3, 3, 1, 0, 1)
Anivia = Champion("Anivia", False, 3, 1, 3, 0, 2, 3)
Annie = Champion("Annie", False, 3, 1, 3, 0, 2, 1)
Ashe = Champion("Ashe", False, 2, 0, 3, 0, 2, 1)
AurelionSol = Champion("Aurelion Sol", False, 3, 0, 2, 2, 0, 3)
Azir = Champion("Azir", False, 3, 1, 2, 2, 1, 3)
Bard = Champion("Bard", False, 1, 1, 3, 2, 3, 3)
Blitzcrank = Champion("Blitzcrank", True, 1, 2, 3, 1, 0, 1)
Brand = Champion("Brand", False, 3, 0, 2, 0, 0, 2)
Braum = Champion("Braum", True, 1, 2, 3, 1, 2, 2)
Caitlyn = Champion("Caitlyn", False, 3, 0, 2, 2, 0, 1)
Camille = Champion("Camille", True, 3, 2, 2, 3, 0, 3)
Cassiopeia = Champion("Cassiopeia", False, 3, 1, 3, 1, 0, 3)
ChoGath = Champion("Cho'Gath", True, 2, 3, 2, 0, 0, 1)
Corki = Champion("Corki", False, 3, 0, 1, 2, 0, 2)
Darius = Champion("Darius", True, 3, 2, 2, 0, 0, 2)
Diana = Champion("Diana", True, 3, 2, 2, 2, 0, 1)
DrMundo = Champion("Dr. Mundo", True, 2, 3, 1, 0, 0, 1)
Draven = Champion("Draven", False, 3, 0, 1, 2, 0, 3)
Ekko = Champion("Ekko", True, 3, 2, 2, 3, 0, 3)
Elise = Champion("Elise", "Mixed", 2, 2, 2, 2, 0, 3)
Evelynn = Champion("Evelynn", True, 2, 2, 1, 2, 2, 2)
Ezreal = Champion("Ezreal", False, 3, 0, 0, 3, 1, 1)
FiddleSticks = Champion("Fiddlesticks", False, 3, 1, 3, 1, 0, 2)
Fiora = Champion("Fiora", True, 3, 2, 2, 2, 2, 3)
Fizz = Champion("Fizz", True, 3, 1, 2, 3, 0, 3)
Galio = Champion("Galio", True, 2, 3, 3, 2, 1, 2)
Gangplank = Champion("Gangplank", True, 3, 1, 1, 1, 2, 3)
Garen = Champion("Garen", True, 2, 3, 1, 1, 0, 1)
Gnar = Champion("Gnar", "Mixed", 2, 1, 1, 2, 0, 3)
Gragas = Champion("Gragas", True, 2, 3, 3, 2, 0, 2)
Graves = Champion("Graves", False, 3, 2, 1, 2, 2, 2)
Hecarim = Champion("Hecarim", True, 2, 2, 2, 2, 0, 2)
Heimerdinger = Champion("Heimerdinger", False, 3, 0, 2, 0, 2, 2)
Illaoi = Champion("Illaoi", True, 3, 2, 1, 0, 0, 2)
Irelia = Champion("Irelia", True, 2, 2, 2, 3, 2, 3)
Ivern = Champion("Ivern", False, 1, 1, 3, 2, 3, 3)
Janna = Champion("Janna", False, 1, 1, 3, 1, 3, 1)
JarvanIV = Champion("Jarvan IV", True, 2, 2, 2, 2, 2, 1)
Jax = Champion("Jax", True, 3, 2, 2, 2, 0, 2)
Jayce = Champion("Jayce", "Mixed", 3, 0, 1, 2, 2, 2)
Jhin = Champion("Jhin", False, 3, 0, 2, 1, 0, 2)
Jinx = Champion("Jinx", False, 3, 0, 2, 1, 0, 2)
KaiSa = Champion("Kai'Sa", False, 3, 1, 0, 3, 1, 2)
Kalista = Champion("Kalista", False, 3, 0, 1, 3, 2, 3)
Karma = Champion("Karma", False, 2, 1, 2, 1, 2, 1)
Karthus = Champion("Karthus", False, 3, 0, 1, 0, 2, 2)
Kassadin = Champion("Kassadin", True, 3, 2, 1, 3, 0, 2)
Katarina = Champion("Katarina", True, 3, 0, 0, 3, 0, 3)
Kayle = Champion("Kayle", "Mixed", 3, 1, 1, 1, 3, 2)
Kayn = Champion("Kayn", True, 3, 1, 1, 3, 1, 2)
Kennen = Champion("Kennen", False, 3, 1, 3, 1, 0, 2)
KhaZix = Champion("Kha'Zix", True, 3, 1, 1, 2, 0, 2)
Kindred = Champion("Kindred", False, 3, 1, 2, 3, 2, 3)
Kled = Champion("Kled", True, 3, 2, 1, 3, 1, 2)
KogMaw = Champion("Kog'Maw", False, 3, 0, 1, 0, 1, 2)
LeBlanc = Champion("LeBlanc", False, 3, 0, 2, 3, 0, 3)
LeeSin = Champion("Lee Sin", True, 3, 2, 2, 3, 1, 3)
Leona = Champion("Leona", True, 1, 3, 3, 1, 1, 1)
Lissandra = Champion("Lissandra", False, 3, 1, 3, 2, 0, 2)
Lucian = Champion("Lucian", False, 3, 0, 0, 3, 0, 2)
Lulu = Champion("Lulu", False, 2, 1, 2, 1, 3, 2)
Lux = Champion("Lux", False, 3, 1, 2, 0, 2, 1)
Malphite = Champion("Malphite", True, 1, 3, 3, 1, 0, 1)
Malzahar = Champion("Malzahar", False, 3, 1, 3, 0, 2, 1)
Maokai = Champion("Maokai", True, 1, 3 , 3, 1, 2, 1)
MasterYi = Champion("Master Yi", True, 3, 1, 0, 2, 0, 1)
MissFortune = Champion("Miss Fortune", False, 3, 0, 1, 1, 0, 1)
Mordekaiser = Champion("Mordekaiser", True, 3, 2, 0, 0, 2, 2)
Morgana = Champion("Morgana", False, 2, 1, 3, 0, 2, 1)
Nami = Champion("Nami", False, 1, 1, 3, 1, 2, 2)
Nasus = Champion("Nasus", True, 2, 3, 2, 0, 1, 1)
Nautilus = Champion("Nautilus", True, 1, 3, 3, 1, 0, 2)
Neeko = Champion("Neeko", True, 3, 1, 3, 1, 1, 1)
Nidalee = Champion("Nidalee", "Mixed", 3, 1, 0, 3, 2, 3)
Nocturne = Champion("Nocturne", True, 3, 1, 2, 2, 2, 1)
Nunu = Champion("Nunu", True, 1, 3, 2, 1, 2, 1)
Olaf = Champion("Olaf", True, 2, 2, 2, 1, 0, 2)
Orianna = Champion("Orianna", False, 2, 1, 2, 1, 2, 2)
Ornn = Champion("Ornn", True, 1, 3, 3, 1, 2, 2)
Pantheon = Champion("Pantheon", True, 3, 2, 2, 2, 0, 1)
Poppy = Champion("Poppy", True, 2, 3, 3, 2, 0, 2)

Rumble = Champion("Rumble", True, 3, 2, 2, 1, 0, 3)




ChampList = [Aatrox,Ahri,Akali,Alistar,Amumu,Anivia,Annie,Ashe,AurelionSol,Azir,Bard,Blitzcrank,Brand,Braum,
             Caitlyn, Camille, Cassiopeia, ChoGath, Corki, Darius, Diana, DrMundo, Draven, Ekko, Elise, Evelynn, Ezreal, FiddleSticks, 
             Fiora, Fizz, Galio, Gangplank, Garen, Gnar, Gragas, Graves, Hecarim, Illaoi, Irelia, Ivern,
             Janna, JarvanIV, Jax, Jayce, Jhin, Jinx, KaiSa, Kalista, Karma, Karthus,Kassadin,Katarina,Kayle,Kayn,
             Kennen,KhaZix,Kindred,Kled,KogMaw,LeBlanc,LeeSin, Leona,Lissandra,Lucian,Lulu,Lux,Malphite,Malzahar,
             Maokai,MasterYi,MissFortune,Mordekaiser,Nami,Nasus,Nautilus,Neeko,Nidalee,Nocturne,Nunu,
             Olaf, Orianna, Ornn, Pantheon, Poppy, Rumble]